jobs:
name: GitHub Metrics
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:


  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: vanilson05
          base: ""
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes
          plugin_activity_skipped: ""
          plugin_activity_load: 300
          config_timezone: America/Sao_Paulo
          config_display: columns
          config_output: svg
          config_presets: ""
          config_order: activity
          config_theme: blue
